name: wedding
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  get_storage: ^2.0.3
  google_fonts: ^6.1.0
  audioplayers: ^5.2.0
  url_launcher: ^6.2.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

dependency_overrides:
  audioplayers:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers'
  audioplayers_platform_interface:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_platform_interface'
  audioplayers_web:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_web'
  audioplayers_linux:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_linux'
  audioplayers_android:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_android'
  audioplayers_darwin:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_darwin'
  audioplayers_windows:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_windows'

flutter: 
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
  fonts:
    - family: Josefin
      fonts:
        - asset: assets/fonts/josefin_sans.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.03523cf.ttf
    - family: Roboto-Light
      fonts:
        - asset: assets/fonts/Roboto-Light.0cea398.ttf
    - family: Roboto-Black
      fonts:
        - asset: assets/fonts/Roboto-Black.1224b64.ttf
    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento-Regular.5bd7d52.ttf