name: wedding
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  get_storage: ^2.0.3
  google_fonts: ^6.1.0
  audioplayers: ^5.2.1
  url_launcher: ^6.2.5
  flutter: 
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  firebase_database: ^10.4.9
  firebase_core: ^2.27.1
  ai_barcode_scanner: ^3.4.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

dependency_overrides:
  web: ^0.3.0

flutter: 
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
  fonts:
    - family: Josefin
      fonts:
        - asset: assets/fonts/josefin_sans.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.03523cf.ttf
    - family: Roboto-Light
      fonts:
        - asset: assets/fonts/Roboto-Light.0cea398.ttf
    - family: Roboto-Black
      fonts:
        - asset: assets/fonts/Roboto-Black.1224b64.ttf
    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento-Regular.5bd7d52.ttf